#define _GNU_SOURCE
#include "efi-identities.h"
#include <errno.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

static const char *old_part = "12345678-9abc-def0-1122-334455667788";
static const char *new_part = "87654321-cba9-0fed-8877-665544332211";
static void die(const char *s) { perror(s); exit(1); }
static void p32(unsigned char *p,uint32_t v){int i;for(i=0;i<4;i++){p[i]=(unsigned char)v;v>>=8;}}
static void p64(unsigned char *p,uint64_t v){int i;for(i=0;i<8;i++){p[i]=(unsigned char)v;v>>=8;}}
static int hx(int c){return c>='0'&&c<='9'?c-'0':c>='a'&&c<='f'?c-'a'+10:c-'A'+10;}
static void guid(const char*s,unsigned char*o){unsigned char b[16];int i,k=0;for(i=0;s[i];){if(s[i]=='-'){i++;continue;}b[k++]=(unsigned char)((hx(s[i])<<4)|hx(s[i+1]));i+=2;}o[0]=b[3];o[1]=b[2];o[2]=b[1];o[3]=b[0];o[4]=b[5];o[5]=b[4];o[6]=b[7];o[7]=b[6];memcpy(o+8,b+8,8);}
static void path(char *o,size_t n,const char*a,const char*b){if(snprintf(o,n,"%s/%s",a,b)>=(int)n)die("path");}
static void writef(const char*p,const void*b,size_t n){int f=open(p,O_WRONLY|O_CREAT|O_TRUNC,0600);if(f<0||write(f,b,n)!=(ssize_t)n||close(f))die("write");}
static uint64_t g64(const unsigned char*p){uint64_t v=0;int i;for(i=7;i>=0;i--)v=(v<<8)|p[i];return v;}
static void replace_all(const char *p,const char *old,const char *nw){char in[8192],out[16384],*cursor,*hit,*at=out;int f=open(p,O_RDONLY);ssize_t n;if(f<0||(n=read(f,in,sizeof(in)-1))<0||close(f))die("replace read");in[n]='\0';cursor=in;while((hit=strstr(cursor,old))){size_t count=(size_t)(hit-cursor);if((size_t)(at-out)+count+strlen(nw)>=sizeof(out))die("replace size");memcpy(at,cursor,count);at+=count;memcpy(at,nw,strlen(nw));at+=strlen(nw);cursor=hit+strlen(old);}if((size_t)(at-out)+strlen(cursor)>=sizeof(out))die("replace tail");strcpy(at,cursor);at+=strlen(cursor);writef(p,out,(size_t)(at-out));}
static int contains(const char *p,const char *s){char b[512];int f=open(p,O_RDONLY);ssize_t n;if(f<0)return 0;n=read(f,b,sizeof(b)-1);close(f);if(n<0)return 0;b[n]='\0';return strstr(b,s)!=NULL;}
static int extra_cases(const char *,const char *,const char *,const char *,const char *,const char *,const char *);
static void run_extra_at_exit(void){const char *base=getenv("ROOTPXE_EFI_EXTRA_CASE");char root[4096],var[4096],mf[4096],pf[4096],res[4096],v1[4096],v2[4096];if(!base)return;path(root,sizeof(root),base,"root");path(var,sizeof(var),root,"efivars");path(mf,sizeof(mf),base,"manifest.json");path(pf,sizeof(pf),base,"plan.json");path(res,sizeof(res),base,"result.json");path(v1,sizeof(v1),var,"Boot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c");path(v2,sizeof(v2),var,"Boot0002-8be4df61-93ca-11d2-aa0d-00e098032b8c");if(extra_cases(root,var,mf,pf,res,v1,v2))_exit(1);}
__attribute__((constructor)) static void register_extra(void){if(atexit(run_extra_at_exit))_exit(1);}
static void make_var(const char *,int,int); static int run(const char *,const char *,const char *,const char *); static void inputs(const char *,const char *,const char *,const char *,const char *,int);
static void attempt_at_exit(void){const char *base=getenv("ROOTPXE_EFI_EXTRA_CASE");char root[4096],var[4096],mf[4096],pf[4096],res[4096],v1[4096],v2[4096];if(!base)return;path(root,sizeof(root),base,"root");path(var,sizeof(var),root,"efivars");path(mf,sizeof(mf),base,"manifest.json");path(pf,sizeof(pf),base,"plan.json");path(res,sizeof(res),base,"result.json");path(v1,sizeof(v1),var,"Boot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c");path(v2,sizeof(v2),var,"Boot0002-8be4df61-93ca-11d2-aa0d-00e098032b8c");make_var(v1,0,0);make_var(v2,1,0);inputs(root,var,mf,pf,"attempt",0);if(run(mf,pf,res,"preflight")){fprintf(stderr,"attempt setup failed\n");_exit(1);}replace_all(pf,"\"attempt\":1","\"attempt\":2");if(run(mf,pf,res,"apply")){fprintf(stderr,"attempt drift was not ignored\n");_exit(1);}}
__attribute__((constructor)) static void register_attempt(void){if(atexit(attempt_at_exit))_exit(1);}
static void safety_at_exit(void){const char *base=getenv("ROOTPXE_EFI_EXTRA_CASE");char root[4096],var[4096],mf[4096],pf[4096],res[4096],v1[4096],v2[4096],bad[4096],cand[4096];if(!base)return;path(root,sizeof(root),base,"root");path(var,sizeof(var),root,"efivars");path(mf,sizeof(mf),base,"manifest.json");path(pf,sizeof(pf),base,"plan.json");path(res,sizeof(res),base,"result.json");path(v1,sizeof(v1),var,"Boot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c");path(v2,sizeof(v2),var,"Boot0002-8be4df61-93ca-11d2-aa0d-00e098032b8c");make_var(v1,0,0);make_var(v2,1,0);inputs(root,var,mf,pf,"broken",0);if(run(mf,pf,res,"preflight")){fprintf(stderr,"broken setup failed\n");_exit(1);}path(cand,sizeof(cand),root,".rootpxe-offline-identities/broken/efi/0.cand");unlink(cand);if(run(mf,pf,res,"apply")==0){fprintf(stderr,"missing candidate accepted\n");_exit(1);}path(bad,sizeof(bad),base,"symlink-root");if(symlink(root,bad))die("symlink");inputs(bad,var,mf,pf,"symlink",0);if(run(mf,pf,res,"preflight")==0){fprintf(stderr,"symlink root accepted\n");_exit(1);}unlink(bad);}
__attribute__((constructor)) static void register_safety(void){if(atexit(safety_at_exit))_exit(1);}
static void json_at_exit(void){const char *base=getenv("ROOTPXE_EFI_EXTRA_CASE");char root[4096],var[4096],mf[4096],pf[4096],res[4096],v1[4096],v2[4096];int f;static const unsigned char nul_tail[]={0,'x'};if(!base)return;path(root,sizeof(root),base,"root");path(var,sizeof(var),root,"efivars");path(mf,sizeof(mf),base,"manifest.json");path(pf,sizeof(pf),base,"plan.json");path(res,sizeof(res),base,"result.json");path(v1,sizeof(v1),var,"Boot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c");path(v2,sizeof(v2),var,"Boot0002-8be4df61-93ca-11d2-aa0d-00e098032b8c");make_var(v1,0,0);make_var(v2,1,0);inputs(root,var,mf,pf,"emptyjson",0);writef(mf,"",0);if(run(mf,pf,res,"preflight")==0){fprintf(stderr,"empty JSON accepted\n");_exit(1);}inputs(root,var,mf,pf,"tailjson",0);f=open(mf,O_WRONLY|O_APPEND);if(f<0||write(f,"x",1)!=1||close(f))die("json tail");if(run(mf,pf,res,"preflight")==0){fprintf(stderr,"JSON tail accepted\n");_exit(1);}inputs(root,var,mf,pf,"nuljson",0);f=open(mf,O_WRONLY|O_APPEND);if(f<0||write(f,nul_tail,sizeof(nul_tail))!=(ssize_t)sizeof(nul_tail)||close(f))die("json nul");if(run(mf,pf,res,"preflight")==0){fprintf(stderr,"JSON NUL tail accepted\n");_exit(1);}}
__attribute__((constructor)) static void register_json(void){if(atexit(json_at_exit))_exit(1);}
static void device_only_at_exit(void){const char *base=getenv("ROOTPXE_EFI_EXTRA_CASE");char root[4096],var[4096],mf[4096],pf[4096],res[4096],v1[4096],v2[4096];if(!base)return;path(root,sizeof(root),base,"root");path(var,sizeof(var),root,"efivars");path(mf,sizeof(mf),base,"manifest.json");path(pf,sizeof(pf),base,"plan.json");path(res,sizeof(res),base,"result.json");path(v1,sizeof(v1),var,"Boot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c");path(v2,sizeof(v2),var,"Boot0002-8be4df61-93ca-11d2-aa0d-00e098032b8c");make_var(v1,0,0);make_var(v2,1,0);inputs(root,var,mf,pf,"deviceonly",0);replace_all(pf,"\"targetDevice\":\"/dev/gpt0p1\",\"number\":1,\"partitionGuid\"","\"targetDevice\":\"/dev/gpt0p1\",\"partitionGuid\"");replace_all(pf,"\"targetDevice\":\"/dev/mbr0p1\",\"number\":1}","\"targetDevice\":\"/dev/mbr0p1\"}");if(run(mf,pf,res,"preflight")){fprintf(stderr,"device-only plan volume rejected\n");_exit(1);}}
__attribute__((constructor)) static void register_device_only(void){if(atexit(device_only_at_exit))_exit(1);}
static void stage_tamper_at_exit(void){const char *base=getenv("ROOTPXE_EFI_EXTRA_CASE");char root[4096],var[4096],mf[4096],pf[4096],res[4096],v1[4096],v2[4096],cand[4096],vars[4096];unsigned char before[60],b[60];int f;if(!base)return;path(root,sizeof(root),base,"root");path(var,sizeof(var),root,"efivars");path(mf,sizeof(mf),base,"manifest.json");path(pf,sizeof(pf),base,"plan.json");path(res,sizeof(res),base,"result.json");path(v1,sizeof(v1),var,"Boot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c");path(v2,sizeof(v2),var,"Boot0002-8be4df61-93ca-11d2-aa0d-00e098032b8c");make_var(v1,0,0);make_var(v2,1,0);inputs(root,var,mf,pf,"canddesc",0);if(run(mf,pf,res,"preflight"))_exit(1);path(cand,sizeof(cand),root,".rootpxe-offline-identities/canddesc/efi/0.cand");f=open(cand,O_RDONLY);if(f<0||read(f,b,60)!=60||close(f))die("cand read");b[10]=1;writef(cand,b,60);f=open(v1,O_RDONLY);if(f<0||read(f,before,60)!=60||close(f))die("orig read");if(run(mf,pf,res,"apply")==0){fprintf(stderr,"description candidate tamper accepted\n");_exit(1);}f=open(v1,O_RDONLY);if(f<0||read(f,b,60)!=60||close(f)||memcmp(b,before,60)){fprintf(stderr,"candidate tamper wrote firmware\n");_exit(1);}make_var(v1,0,0);make_var(v2,1,0);inputs(root,var,mf,pf,"emptyvars",0);if(run(mf,pf,res,"preflight"))_exit(1);path(vars,sizeof(vars),root,".rootpxe-offline-identities/emptyvars/efi/vars");writef(vars,"count=0\n",8);if(run(mf,pf,res,"apply")==0){fprintf(stderr,"empty vars accepted\n");_exit(1);}}
__attribute__((constructor)) static void register_stage_tamper(void){if(atexit(stage_tamper_at_exit))_exit(1);}
static void list_tamper_at_exit(void){const char *base=getenv("ROOTPXE_EFI_EXTRA_CASE");char root[4096],var[4096],mf[4096],pf[4096],res[4096],v1[4096],v2[4096],cand[4096],vars[4096];unsigned char b[60];int f;const char *one="count=1\nBoot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c\n";const char *dup="count=2\nBoot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c\nBoot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c\n";if(!base)return;path(root,sizeof(root),base,"root");path(var,sizeof(var),root,"efivars");path(mf,sizeof(mf),base,"manifest.json");path(pf,sizeof(pf),base,"plan.json");path(res,sizeof(res),base,"result.json");path(v1,sizeof(v1),var,"Boot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c");path(v2,sizeof(v2),var,"Boot0002-8be4df61-93ca-11d2-aa0d-00e098032b8c");make_var(v1,0,0);make_var(v2,1,0);inputs(root,var,mf,pf,"optional",0);if(run(mf,pf,res,"preflight"))_exit(1);path(cand,sizeof(cand),root,".rootpxe-offline-identities/optional/efi/0.cand");f=open(cand,O_RDONLY);if(f<0||read(f,b,60)!=60||close(f))die("optional read");b[58]^=1;writef(cand,b,60);if(run(mf,pf,res,"apply")==0){fprintf(stderr,"optional candidate tamper accepted\n");_exit(1);}make_var(v1,0,0);make_var(v2,1,0);inputs(root,var,mf,pf,"deletedvars",0);if(run(mf,pf,res,"preflight"))_exit(1);path(vars,sizeof(vars),root,".rootpxe-offline-identities/deletedvars/efi/vars");writef(vars,one,strlen(one));if(run(mf,pf,res,"apply")==0){fprintf(stderr,"deleted vars accepted\n");_exit(1);}make_var(v1,0,0);make_var(v2,1,0);inputs(root,var,mf,pf,"duplicatevars",0);if(run(mf,pf,res,"preflight"))_exit(1);path(vars,sizeof(vars),root,".rootpxe-offline-identities/duplicatevars/efi/vars");writef(vars,dup,strlen(dup));if(run(mf,pf,res,"apply")==0){fprintf(stderr,"duplicate vars accepted\n");_exit(1);}}
__attribute__((constructor)) static void register_list_tamper(void){if(atexit(list_tamper_at_exit))_exit(1);}
static void make_var(const char*p,int mbr,int bad){unsigned char b[64]={0};size_t o=12;b[0]=7;b[4]=1;p32(b+8,46);b[o]=4;b[o+1]=1;p32(b+o+2,42);p32(b+o+4,1);p64(b+o+8,8);p64(b+o+16,8);if(mbr)p32(b+o+24,0xf1234567U);else guid(old_part,b+o+24);b[o+40]=mbr?1:2;b[o+41]=mbr?1:2;b[54]=bad?9:0x7f;b[55]=bad?1:0xff;p32(b+56,4);writef(p,b,60);}
static void make_4kn_var(const char*p,int mbr){unsigned char b[60];int f;make_var(p,mbr,0);f=open(p,O_RDONLY);if(f<0||read(f,b,sizeof(b))!=(ssize_t)sizeof(b)||close(f))die("4kn read");p64(b+20,1);p64(b+28,1);b[58]=0xa5;b[59]=0x5a;writef(p,b,sizeof(b));}
static int run(const char*m,const char*p,const char*r,const char*phase){char *a[]={"efi-repair","--manifest",(char*)m,"--plan",(char*)p,"--result",(char*)r,"--phase",(char*)phase};return rootpxe_efi_main(9,a);}
static void inputs(const char *root,const char *var,const char *mf,const char *pf,const char *id,int duplicate){char b[8192];int n;n=snprintf(b,sizeof(b),"{\"version\":1,\"stateRoot\":\"%s\",\"efiVarFs\":\"%s\",\"volumes\":[{\"diskBinding\":\"gpt0\",\"partitionNumber\":1,\"partitionTable\":\"gpt\",\"oldDiskId\":\"11111111-2222-3333-4444-555555555555\",\"newDiskId\":\"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee\",\"oldPartitionGuid\":\"%s\",\"newPartitionGuid\":\"%s\",\"oldOffsetBytes\":4096,\"newOffsetBytes\":8192,\"oldSizeBytes\":4096,\"newSizeBytes\":8192,\"oldLogicalSectorBytes\":512,\"newLogicalSectorBytes\":512},{\"diskBinding\":\"mbr0\",\"partitionNumber\":1,\"partitionTable\":\"mbr\",\"oldDiskId\":\"f1234567\",\"newDiskId\":\"0000000a\",\"oldPartitionGuid\":\"f1234567:1\",\"oldOffsetBytes\":4096,\"newOffsetBytes\":8192,\"oldSizeBytes\":4096,\"newSizeBytes\":8192,\"oldLogicalSectorBytes\":512,\"newLogicalSectorBytes\":512}]}",root,var,old_part,new_part);writef(mf,b,(size_t)n);n=snprintf(b,sizeof(b),"{\"plan\":{\"version\":1,\"planId\":\"%s\",\"topology\":{\"disks\":[{\"targetDevice\":\"/dev/gpt0\",\"targetBinding\":\"%s\",\"partitionTable\":\"gpt\",\"oldDiskId\":\"11111111-2222-3333-4444-555555555555\",\"partitions\":[{\"targetDevice\":\"/dev/gpt0p1\",\"number\":1,\"oldPartitionId\":\"%s\"}]},{\"targetDevice\":\"/dev/mbr0\",\"targetBinding\":\"mbr0\",\"partitionTable\":\"mbr\",\"oldDiskId\":\"f1234567\",\"partitions\":[{\"targetDevice\":\"/dev/mbr0p1\",\"number\":1,\"oldPartitionId\":\"f1234567:1\"}]}]},\"disks\":[{\"targetDevice\":\"/dev/gpt0\",\"diskGuid\":\"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee\",\"partitions\":[{\"targetDevice\":\"/dev/gpt0p1\",\"number\":1,\"partitionGuid\":\"%s\"}]},{\"targetDevice\":\"/dev/mbr0\",\"diskSignature\":\"0000000a\",\"partitions\":[{\"targetDevice\":\"/dev/mbr0p1\",\"number\":1}]}]},\"planHash\":\"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\",\"attempt\":1}",id,duplicate?"mbr0":"gpt0",old_part,new_part);writef(pf,b,(size_t)n);}
static int extra_cases(const char *root,const char *var,const char *mf,const char *pf,const char *res,const char *v1,const char *v2){unsigned char before[60],after[60];int f;make_4kn_var(v1,0);make_4kn_var(v2,1);inputs(root,var,mf,pf,"fourkn",0);replace_all(mf,"512","4096");f=open(v1,O_RDONLY);if(f<0||read(f,before,60)!=60||close(f))die("4kn before");if(run(mf,pf,res,"preflight")||!contains(res,"\"matched\":2,\"updated\":0")){fprintf(stderr,"4Kn preflight counts failed\n");return 1;}f=open(v1,O_RDONLY);if(f<0||read(f,after,60)!=60||close(f)||memcmp(before,after,60)){fprintf(stderr,"4Kn preflight wrote firmware\n");return 1;}if(run(mf,pf,res,"apply")||!contains(res,"\"matched\":2,\"updated\":2")){fprintf(stderr,"4Kn apply counts failed\n");return 1;}f=open(v1,O_RDONLY);if(f<0||read(f,after,60)!=60||close(f)||g64(after+20)!=2||g64(after+28)!=2||memcmp(before,after,20)||memcmp(before+52,after+52,8)){fprintf(stderr,"4Kn conversion or preserved bytes failed\n");return 1;}make_var(v1,0,0);make_var(v2,1,0);inputs(root,var,mf,pf,"nondiv",0);replace_all(mf,"\"oldOffsetBytes\":4096","\"oldOffsetBytes\":4097");f=open(v1,O_RDONLY);if(f<0||read(f,before,60)!=60||close(f))die("nondiv before");if(run(mf,pf,res,"preflight")==0){fprintf(stderr,"nondiv accepted\n");return 1;}f=open(v1,O_RDONLY);if(f<0||read(f,after,60)!=60||close(f)||memcmp(before,after,60)){fprintf(stderr,"nondiv wrote firmware\n");return 1;}make_var(v1,0,0);make_var(v2,1,0);inputs(root,var,mf,pf,"driftmanifest",0);if(run(mf,pf,res,"preflight")){fprintf(stderr,"manifest drift setup failed\n");return 1;}replace_all(mf,"\"oldSizeBytes\":4096","\"oldSizeBytes\":8192");f=open(v1,O_RDONLY);if(f<0||read(f,before,60)!=60||close(f))die("manifest drift before");if(run(mf,pf,res,"apply")==0){fprintf(stderr,"manifest drift accepted\n");return 1;}f=open(v1,O_RDONLY);if(f<0||read(f,after,60)!=60||close(f)||memcmp(before,after,60)){fprintf(stderr,"manifest drift wrote firmware\n");return 1;}make_var(v1,0,0);make_var(v2,1,0);inputs(root,var,mf,pf,"driftplan",0);if(run(mf,pf,res,"preflight")){fprintf(stderr,"plan drift setup failed\n");return 1;}replace_all(pf,"\"planHash\":\"a","\"planHash\":\"b");f=open(v1,O_RDONLY);if(f<0||read(f,before,60)!=60||close(f))die("plan drift before");if(run(mf,pf,res,"apply")==0){fprintf(stderr,"plan drift accepted\n");return 1;}f=open(v1,O_RDONLY);if(f<0||read(f,after,60)!=60||close(f)||memcmp(before,after,60)){fprintf(stderr,"plan drift wrote firmware\n");return 1;}return 0;}
int main(int argc,char**argv){char root[4096],var[4096],mf[4096],pf[4096],res[4096],v1[4096],v2[4096],bad[4096];unsigned char before[60],after[60];int f;if(argc!=2)return 2;path(root,sizeof(root),argv[1],"root");path(var,sizeof(var),root,"efivars");if(mkdir(argv[1],0700)&&errno!=EEXIST)die("tmp");if(mkdir(root,0700)&&errno!=EEXIST)die("root");if(mkdir(var,0700)&&errno!=EEXIST)die("efivars");path(mf,sizeof(mf),argv[1],"manifest.json");path(pf,sizeof(pf),argv[1],"plan.json");path(res,sizeof(res),argv[1],"result.json");path(v1,sizeof(v1),var,"Boot0001-8be4df61-93ca-11d2-aa0d-00e098032b8c");path(v2,sizeof(v2),var,"Boot0002-8be4df61-93ca-11d2-aa0d-00e098032b8c");make_var(v1,0,0);make_var(v2,1,0);inputs(root,var,mf,pf,"lifecycle",0);f=open(v1,O_RDONLY);if(f<0||read(f,before,60)!=60||close(f))die("read before");if(run(mf,pf,res,"verify")==0||run(mf,pf,res,"preflight")||run(mf,pf,res,"verify")==0) {fprintf(stderr,"phase guard failed\n");return 1;}f=open(v1,O_RDONLY);if(f<0||read(f,after,60)!=60||close(f)||memcmp(before,after,60)){fprintf(stderr,"preflight wrote firmware\n");return 1;}/* simulate interrupted first variable install */{char c[4096];path(c,sizeof(c),root,".rootpxe-offline-identities/lifecycle/efi/0.cand");f=open(c,O_RDONLY);if(f<0||read(f,after,60)!=60||close(f))die("candidate");writef(v1,after,60);}if(run(mf,pf,res,"apply")||run(mf,pf,res,"verify")||run(mf,pf,res,"apply")){fprintf(stderr,"lifecycle failed\n");return 1;}f=open(v1,O_RDONLY);if(f<0||read(f,after,60)!=60||close(f)||after[20]!=16||after[36]!=0x21||after[37]!=0x43){fprintf(stderr,"GPT repair failed\n");return 1;}f=open(v2,O_RDONLY);if(f<0||read(f,after,60)!=60||close(f)||after[20]!=16||after[36]!=10){fprintf(stderr,"MBR repair failed\n");return 1;}/* malformed and ambiguous paths must reject during preflight. */path(bad,sizeof(bad),var,"Boot0003-8be4df61-93ca-11d2-aa0d-00e098032b8c");make_var(bad,0,1);inputs(root,var,mf,pf,"malformed",0);if(run(mf,pf,res,"preflight")==0){fprintf(stderr,"malformed accepted\n");return 1;}unlink(bad);make_var(v1,0,0);inputs(root,var,mf,pf,"ambiguous",1);if(run(mf,pf,res,"preflight")==0){fprintf(stderr,"ambiguous accepted\n");return 1;}puts("PASS: EFI GPT/MBR lifecycle, preflight, partial recovery, malformed and ambiguous fixtures");return 0;}
