#!/bin/bash
#
#
# rc.single     This file is executed by init when it goes into runlevel
#               1, which is the administrative state. It kills all
#               deamons and then puts the system into single user mode.
#               Note that the file systems are kept mounted.
#
# Author:       Miquel van Smoorenburg, <miquels@drinkel.nl.mugnet.org>
#               Modified for RHS Linux by Damien Neil
#               Modified for FOG by Chuck Syperski
#
[[ ! -h /dev/fd ]] && ln -s /proc/self/fd /dev/fd
[[ ! -h /dev/stdin ]] && ln -s /proc/self/fd/0 /dev/stdin
[[ ! -h /dev/stdout ]] && ln -s /proc/self/fd/1 /dev/stdout
[[ ! -h /dev/stderr ]] && ln -s /proc/self/fd/2 /dev/stderr
if [[ $mdraid == true ]]; then
    mdadm --auto-detect
    mdadm --assemble --scan
    mdadm --incremental --run --scan
fi
[[ -n $keymap ]] && loadkeys $keymap

case $isdebug in
    [Yy][Ee][Ss]|[Yy])
        pxeos.debug
        ;;
    *)
        pxeos
        rc=$?
        if [[ $rc -eq 0 ]]; then
            sleep 5 >/dev/null 2>&1
            echo " * Rebooting system as task is complete"
            # 优先读取 checkin 下发并落盘的 shutdown（0/1）
            shutdown_local="$shutdown"
            if [[ -f /tmp/pxeos.shutdown ]]; then
                shutdown_local="$(tr -d '\r\n\0' </tmp/pxeos.shutdown)"
            fi
            [[ "$shutdown_local" == "1" ]] && poweroff || reboot -f
        else
            echo " * PXEOS task exited with error (rc=$rc), keeping system for troubleshooting"
            echo " * Tip: add 'isdebug=yes' in kernel args for interactive debug mode"
            sleep 300
        fi
        ;;
esac
